# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.60.1"
default_platform :android
gradle_path = './gradlew'
default_platform:android

platform:android do
  lane :test do |values|
    buildType = values[:buildType] ? "-PbuildType='#{values[:buildType]}'" : ''
    testType = values[:testType] ? values[:testType] : 'TDD'
    tags = values[:tags] ? "-Ptags='#{values[:tags]}'" : ''
    features = values[:features] ? "-Pfeatures='#{values[:features]}'" : ''

    #clear output reports
    gradle(task: 'clearOutput')

    case testType
        when 'Unit'
            desc "Gradle Run Unit Test "
            gradle(task: 'runUnitTest')
        when 'UI'
            desc "Gradle Run UI Test "
            gradle(task: "runUiTest #{buildType} #{features} #{tags}")
        when 'ALL'
            desc "Gradle Run Unit and UI Test "
            gradle(task: 'runUnitTest')
            gradle(task: "runUiTest #{buildType} #{features} #{tags}")
    end

  end
end

#======================================================================
#Run in Gradle
#UNIT TEST:
#gradlew runUnitTest -PbuildType="Debug"

#UI TEST:
#gradlew runUiTest -PbuildType="Debug"
#gradlew runUiTest -PbuildType="Release"

#增加test範圍條件features或tags
#gradlew runUiTest -PbuildType="Debug" -Ptags="@Main"
#gradlew runUiTest -PbuildType="Debug" -Ptags="@Login,@Text"
#gradlew runUiTest -PbuildType="Debug" -Pfeatures="crucial"
#gradlew runUiTest -PbuildType="Debug" -Pfeatures="crucial" -Ptags="@Main"

#======================================================================
#Run in Fastlane:
#fastlane android test buildType:Debug testType:TDD
#fastlane android test buildType:Debug testType:BDD
#fastlane android test buildType:Debug testType:ALL

#限制UI test範圍條件features或tags
#fastlane android test buildType:Debug testType:BDD tags:@Login,@Text
#fastlane android test buildType:Debug testType:ALL tags:@Main
#fastlane android test buildType:Debug testType:ALL features:crucial tags:@Main
#fastlane android test buildType:Debug testType:ALL features:crucial

#屬性說明======================================================================
#buildType:(駝峰式命名)
#Debug
#Release
#Stage(不一定有，依據App Project定義)
#======================================================================
#testType:
#UNIT
#UI
#ALL
#======================================================================
#tags:(可一次多個，駝峰式命名)
#@Login
#@Main
#@Login,@Main
#=======================================================================
#features:(依據測試等級分類範圍的定義，UI TEST的Feature也要對應的分層資料夾)
#low
#medium
#crucial
#=======================================================================
